LeaveManagment.Mvc/Models/ErrorViewModel.cs
namespace LeaveManagment.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LeaveManagment.Mvc/Models/LeaveTypes/CreateLeaveTypeVM.cs
using System.ComponentModel.DataAnnotations;

namespace LeaveManagment.Mvc.Models.LeaveTypes
{
    public class UpdateLeaveTypeVM : LeaveTypeVM
    {

    }
}

LeaveManagment.Mvc/Models/LeaveTypes/LeaveTypeVM.cs
using System.ComponentModel.DataAnnotations;

namespace LeaveManagment.Mvc.Models.LeaveTypes
{
    public class LeaveTypeVM : CreateLeaveTypeVM
    {
        public int Id { get; set; }

    }
}

LeaveManagment.Mvc/Models/LeaveTypes/UpdateLeaveTypeVM.cs
using System.ComponentModel.DataAnnotations;

namespace LeaveManagment.Mvc.Models.LeaveTypes
{
    public class CreateLeaveTypeVM
    {
        [Required]
        public string Name { get; set; }


        [Required]
        [Display(Name = "Default Number of Days")]
        public int DefaultDay { get; set; }
    }
}

LeaveManagment.Mvc/Controllers/HomeController.cs
using LeaveManagment.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LeaveManagment.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LeaveManagment.Mvc/Controllers/LeaveTypesController.cs
using LeaveManagment.Mvc.Contratcs;
using LeaveManagment.Mvc.Models.LeaveTypes;
using LeaveManagment.Mvc.Services.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LeaveManagment.Mvc.Controllers
{
    [Authorize]
    public class LeaveTypesController : Controller
    {
        private readonly ILeaveTypeService _leaveTypeService;

        public LeaveTypesController(ILeaveTypeService leaveTypeService)
        {
            _leaveTypeService = leaveTypeService;
        }
        // GET: LeaveTypesController
        public async Task<ActionResult> Index()
        {
            var leaveTypes = await _leaveTypeService.GetLeaveTypes();

            return View(leaveTypes);
        }

        // GET: LeaveTypesController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var leaveTypes = await _leaveTypeService.GetLeaveTypeDetails(id);
            return View(leaveTypes);
        }

        // GET: LeaveTypesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveTypeVM createLeaveTypeVM)
        {
            try
            {
                var response = await _leaveTypeService.CreateLeaveType(createLeaveTypeVM);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                else{
                    ModelState.AddModelError("", response.ValidationErrors);
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

            }          
            return View(createLeaveTypeVM);

        }

        // GET: LeaveTypesController/Edit/5
        public async Task< ActionResult> Edit(int id)
        {
            var result= await _leaveTypeService.GetLeaveTypeDetails(id);
            var updateLeaveType = new UpdateLeaveTypeVM {Id=result.Id,DefaultDay=result.DefaultDay,Name=result.Name };
            return View(updateLeaveType);
        }

        // POST: LeaveTypesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateLeaveTypeVM updateLeaveTypeVM)
        {
            try
            {
                var response = await _leaveTypeService.UpdateLeaveType(id, updateLeaveTypeVM);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", response.ValidationErrors);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

            }
            return View(updateLeaveTypeVM);
        }

        // GET: LeaveTypesController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var leaveTypes = await _leaveTypeService.GetLeaveTypeDetails(id);
            return View(leaveTypes);
        }

        // POST: LeaveTypesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, LeaveTypeVM leaveTypeVM)
        {
            try
            {
                var response = await _leaveTypeService.DeleteLeaveType(id);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", response.ValidationErrors);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

            }
            return View(leaveTypeVM);
        }
    }
}

LeaveManagment.Mvc/Controllers/UsersController.cs
using LeaveManagment.Mvc.Contratcs;
using LeaveManagment.Mvc.Models.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LeaveManagment.Mvc.Controllers
{
    public class UsersController : Controller
    {
        private readonly IAuthenticateService _authenticateService;

        public UsersController(IAuthenticateService authenticateService)
        {
            _authenticateService = authenticateService;
        }

        #region Login

        // GET: UsersController/Login
        public IActionResult Login(string returnUrl = null)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM login, string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            var isLoggedIn = await _authenticateService.AuthenticateAsync(login.Email, login.Password);
            if (isLoggedIn)
            {
                return LocalRedirect(returnUrl);
            }
            ModelState.AddModelError("", "Login feild. Try again.");
            return View(login);
        }
        #endregion

        #region Logout
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
          await  _authenticateService.LogoutAsync();
            return LocalRedirect("/Users/Login");
        }
        #endregion

        #region Register


        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterVM registerVM)
        {
            if (!ModelState.IsValid)
            {
                return View(registerVM);
            }
            var isRegistered=await _authenticateService.RegisterAsync(registerVM);
            if (isRegistered)
            {
                return LocalRedirect("/");
            }

            return View(registerVM);
        }
        #endregion


    }
}

LeaveManagment.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LeaveManagment.Mvc/Views/LeaveTypes/Create.cshtml
@model LeaveManagment.Mvc.Models.LeaveTypes.CreateLeaveTypeVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateLeaveTypeVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefaultDay" class="control-label"></label>
                <input asp-for="DefaultDay" class="form-control" />
                <span asp-validation-for="DefaultDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeaveManagment.Mvc/Views/LeaveTypes/Delete.cshtml
@model LeaveManagment.Mvc.Models.LeaveTypes.LeaveTypeVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LeaveTypeVM</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DefaultDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DefaultDay)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" /> |

        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LeaveManagment.Mvc/Views/LeaveTypes/Details.cshtml
@model LeaveManagment.Mvc.Models.LeaveTypes.LeaveTypeVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LeaveTypeVM</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DefaultDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DefaultDay)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

LeaveManagment.Mvc/Views/LeaveTypes/Edit.cshtml
@model LeaveManagment.Mvc.Models.LeaveTypes.UpdateLeaveTypeVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LeaveTypeVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" type="hidden"/>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefaultDay" class="control-label"></label>
                <input asp-for="DefaultDay" class="form-control" />
                <span asp-validation-for="DefaultDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeaveManagment.Mvc/Views/LeaveTypes/Index.cshtml
@model IEnumerable<LeaveManagment.Mvc.Models.LeaveTypes.LeaveTypeVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DefaultDay)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DefaultDay)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.Id  },  new { @class = "btn btn-warning btn-xs" }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id },  new { @class = "btn btn-info btn-xs" }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id } , new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
}
    </tbody>
</table>

LeaveManagment.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeaveManagment.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeaveManagment.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LeaveManagment.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_LoggedInPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1402 - LeaveManagment.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LeaveManagment.Mvc/Views/Shared/_LoggedInPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action=""> @User.Identity.Name</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="LeaveTypes" asp-action="Index">Leave Types</a>
    </li>

    <form class="form-inline" method="post" asp-action="Logout" asp-controller="Users" asp-area="">
        <button type="submit" class="nav-link btn btn-link">Logout</button>
    </form>

}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
    </li>
}

LeaveManagment.Mvc/Views/Users/Login.cshtml
@model LeaveManagment.Mvc.Models.Identity.LoginVM

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<h4>LoginVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="ReturnUrl" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeaveManagment.Mvc/Views/Users/Register.cshtml
@model LeaveManagment.Mvc.Models.Identity.RegisterVM

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>RegisterVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}